server:
  port: 10010
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stomp-port: 61613
    username: root
    password: root
    virtual-host: /ws
    listener:
      simple:
        acknowledge-mode: auto
