spring:
  # ShardingSphere 配置项
  shardingsphere:
    datasource:
      names: ds-orders-0, ds-orders-1
      ds-orders-0:
        # 使用 Hikari 数据库连接池
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/lab18_orders_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      ds-orders-1:
        # 使用 Hikari 数据库连接池
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/lab18_orders_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    # 分片规则
    sharding:
      tables:
        # orders 表配置
        orders:
          # 映射到 ds-orders-0 和 ds-orders-1 数据源的 orders 表们
          actualDataNodes: ds-orders-0.orders_$->{[0,2,4,6]}, ds-orders-1.orders_$->{[1,3,5,7]}
          # 主键生成策略
          key-generator:
            column: id
            type: SNOWFLAKE
          # 分库策略
          database-strategy:
            inline:
              # 算法表达式 模2
              algorithm-expression: ds-orders-$->{user_id % 2}
              # 字段
              sharding-column: user_id
          # 分表策略
          table-strategy:
            inline:
              # 算法表达式 模8
              algorithm-expression: orders_$->{user_id % 8}
              # 字段
              sharding-column: user_id
        # order_config 表配置
        order_config:
          # 仅映射到 ds-orders-0 数据源的 order_config 表
          actualDataNodes: ds-orders-0.order_config
    # 拓展属性配置
    props:
      # 打印 SQL
      sql:
        show: true